[package]
name = "excercise1"
version = "0.1.0"
authors = ["harish"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="lib"
path="src/lib.rs"
[dependencies]

chrono = "0.4"
clap = "~2.27.0"
